### ISSUE TITLE
MT: load spike every 6 hours (mostly/only dev)

### ISSUE THREAD

**Issue by Dieterbe** [raintank/raintank-metric#105]
every 6hours, for me at 1,7AM, 1, 7PM there's an MT load spike/response time spike.
we only have graphite-api & NMT graphs for dev, not prod, so hard to tell if the issue is only on dev, but the other symptoms are not really visible on prod.

symptoms:

* incoming metrics temporarily drops, an nsq metrics backlog (channel depth) builds up to a few thousand, though it recovers after a few minutes.
https://grafana-monitor.raintank.io/dashboard/snapshot/hEs1R3ad1QWBhDdYj0S0gdzl79rO5A3l
https://grafana-monitor.raintank.io/dashboard/snapshot/QUFa9t9pVNxJox2ng7iCiaTNKFCGUajo
* MT request handling can take >=1s to be served. https://grafana-monitor.raintank.io/dashboard/snapshot/j7OQYJWMUIRGee1KbOx4dOqDtNKwsRCI

* statsd metrics volume spikes https://grafana-monitor.raintank.io/dashboard/snapshot/zLAKdWB5EQmlvBAufU0SmPgdQBef96QD
* cpu spikes to 100% (only 1 core though!), also only seeing this effect on dev. production looks fine, even though i checked that metric-tank-1.prod is currently primary there https://grafana-monitor.raintank.io/dashboard/snapshot/3xai2GI7FqHr3n2KEVZgbIhuh0x4Cf72

metric-tank-1 (dev):
![dev-prof](https://cloud.githubusercontent.com/assets/20774/12251035/6f08e32e-b930-11e5-9dc7-e1f26d273664.png)

i also got a profile on metric-tank-1.prod (primary), there processWriteQueue is only 12%
it suffers a lot more from the EnsureIndex stuff , which at a chunkSpan boundary just gets less visible, from 50% of cpu to 38%.

not sure why it's every 6hours, and why the ratio of processWriteQueue overhead to EnsureIndex overhead is higher on dev. maybe because dev has aggregation enabled and so flushes many more chunks.

clearly what needs to be done (and what i will do) is lower the statsd metrics when saving chunks.  maybe introduce some sampling based on how many chunks there are to save.

**Comment by Dieterbe** [comment]
or just switching to https://github.com/alexcesaro/statsd, the current go statsd client doesn't buffer, this seems like a much better+faster one. just need to look into it a bit more.

**Comment by woodsaj** [comment]
The spikes are 100% related to persisting aggregated chunks.  Current aggSettings are
`agg-settings = 600:21600:2,7200:21600:2,21600:21600:2`  So on every 6th hour all aggregated chunks are persisted.  the timing will be at 6:00, 12:00, 18:00, 00:00 UTC

each aggregation creates 6 new series for each original series.  so with 3 aggregations, we end up with 19x the number of raw series. (raw + 6x10min + 6*2hour + 6*6hour)

**Comment by woodsaj** [comment]
This may also be due to the metricPersist messages. We are currently using using JSON for transport, so marshaling and unmarshaling could be a cause of the high CPU. These are sent using a single goroutine which would explain why only 1 core gets maxed out.  We should switch these to use msgpack.

**Comment by Dieterbe** [comment]
@woodsaj aha so that explains the prod-dev difference. i took a cpu profile yesterday on dev and processWriteQueue was causing the majority of the cpu load (makes sense given the increased chunk saving load due to aggregation). within processWriteQueue, cpu time was split roughly 50/50 between gocql code and the statsd client. i tested and verified the statsd client i mentioned above and it came about about 30x faster. so i'm pretty confident that with https://github.com/raintank/grafana/pull/548, and recompiling MT against it and promoting it to primary will significantly lower the cpu load during these spikes.
when i profiled, json was overshadowed by statsd, but maybe that will be the next step after this. profiling after rolling this out will tell.

**Comment by Dieterbe** [comment]
yesterday we upgraded metric-tank-2 with the fix and promoted it earlier today.
i got a profile and statsd doesn't even come up in it anymore. all processWriteQueue overhead is now attributed to gocql (and some fmt.Sprintf allocations)

and the cpu spike is less intense/shorter as well:
https://grafana-monitor.raintank.io/dashboard/snapshot/eECOdOWFKN56COhz9faLoG0vXr6e2Jmx

however, it seems the spike characteristics (in terms of processing inbound metrics, and response times up to 1.5s) haven't changed one bit. the following look exactly the same:

* 6h ago on metric-tank-1: https://grafana-monitor.raintank.io/dashboard/snapshot/R4BpsRyM8A0822QtJpxlHvNkug5gU5Rg
* now on metric-tank-2: https://grafana-monitor.raintank.io/dashboard/snapshot/Ogkcp4jQWEMwCEfWiRjek4rhx1Z61ElX

i did notice metric-tank-2 had some slower cassandra writes, i started looking into it and found out that
it's configured with `cassandra-write-queue-size = 100000`, but it has metrics_active of 26k, times 19 for all aggregation series, and we get 494k, so what is happening is the write queue fills up and this is why it blocks incoming metrics processing and nsq builds a backlog. and why that problem looks still exactly the same despite the somewhat overall lower cpu usage.

so here's what i think:
* our primary should always have `cassandra-write-queue-size > metrics_active * 19`
* #104 will definitely lower overall cpu even more
* after these two, having 10 concurrent writers to cassandra will probably still max out our cpu, due to the gocl usage.  so we can lower the amount of concurrent writers, spread write load over time (see #99), increase our cores, or try to find out how we can lower gocql cpu usage.  if we could insert several chunks within 1 cassandra query that would probably help as well. @woodsaj do you know if this is possible?

**Comment by woodsaj** [comment]
Cassandra does have a batch API method, but it is designed for making a batch of operations atomic (ie a transaction). If one item in the batch fails the whole batch fails.   As such, using batches puts additional strain on Cassandra.

**Comment by Dieterbe** [comment]
@ctdk can you bump cassandra-write-queue-size on dev to 1 million. this setting should be a good number for the current load of 26k active metrics and will remain a good setting until we hit about 52k active metrics. (as usual, do it smoothly, restart the secondary, and upgrade it to primary the day after or so)

**Comment by ctdk** [comment]
@Dieterbe Certainly. I've changed the setting in the development environment and restarted the secondary (which in this case was metric-tank-1). I disabled chef on metric-tank-2 until confirming that merely updating that setting would not restart metric_tank (it didn't), so tomorrow afternoon I'll promote metric-tank-1 and restart metric-tank-2.

**Comment by Dieterbe** [comment]
ok

**Comment by Dieterbe** [comment]
unfortunately, and surprisingly, ct's config fix didn't really fix it.
metric-tank-1 showed the similar spikes again after being promoted, but perhaps a little smaller.
https://grafana-monitor.raintank.io/dashboard/snapshot/FLeQ4jZzLhKzWat59vOnYxIpqPE6rW07

anyway, since dev is gone now, and not seeing it in prod, going to close it.
