### ISSUE TITLE
resume where we left off after downtime

### ISSUE THREAD

**Issue by Dieterbe** [raintank/raintank-metric#12]
i hear if raintank-metric goes down and comes back up later, i doesn't get the data from rabbitmq it missed. we should fix this. that said I do think the realtime stream is much more important than historical data.  It's not worth it delaying ingestion of our real time metrics by several hours because we have to catch up on a days worth of old data.
I would rather have a high prio real-time stream and a lower QOS stream for the historical data.

**Comment by woodsaj** [comment]
we are using a consistent-hash exchange for the metrics.   When messages are received by the exchange they are routed to 1 of the bound queues.    When a raintank-metric process starts it creates a rabbitmq queue and binds it to the exchange.  When the process dies, the queue is deleted.  So if there are now raintank-metric process running then there are no queues to feed messages to and they will be dropped.

This is just a limitation of the consistant-hash exchange, though in reality there should always be at least 1 raintank-metric process running.

There are a number of changes we can make to address this, but i think that conversation is best had in issue #11

**Comment by woodsaj** [comment]
this is no longer relevant since moving to NSQ
