### ISSUE TITLE
"only add medf to cache after queing for write in ES.": why?

### ISSUE THREAD

**Issue by Dieterbe** [raintank/raintank-metric#120]
@woodsaj why https://github.com/raintank/raintank-metric/commit/4a11a75fc48149a97a2bb9919420ab1ff2f5ebed ?

**Comment by woodsaj** [comment]
from before my commit.

you already knew that the metricDef wasnt in the Cache from
https://github.com/raintank/raintank-metric/blob/0cb96cb1fcfba04bbf2e2e8ea3fba76b2985c3c3/metric_tank/defcache.go#L72

So
https://github.com/raintank/raintank-metric/blob/0cb96cb1fcfba04bbf2e2e8ea3fba76b2985c3c3/metric_tank/defcache.go#L83-L85
is redundant

You already add the metricDef here.
https://github.com/raintank/raintank-metric/bloub/0cb96cb1fcfba04bbf2e2e8ea3fba76b2985c3c3/metric_tank/defcache.go#L108-L110

so the
https://github.com/raintank/raintank-metric/blob/0cb96cb1fcfba04bbf2e2e8ea3fba76b2985c3c3/metric_tank/defcache.go#L86-L91
Isnt needed.

end result, you end up with my commit.

https://github.com/raintank/raintank-metric/blob/0cb96cb1fcfba04bbf2e2e8ea3fba76b2985c3c3/metric_tank/defcache.go#L99 will only fail if the metric cant be added to the bulkIndexer buffer, after that the bulkIndexer will retry until it can send the buffer to ES.  If we cant write to the bulkIndexer then we would need to retry the next time we see the metric.  If we added the metricDef to the cache and failed `metricdef.IndexMetric(mdef)` failed then we would not retry to index it for many hours.

**Comment by Dieterbe** [comment]
the reason for the 2nd defcache check is to see if another message handler may have added the metricdef in the meantime. while the probability seems low, this is still useful: we can avoid doing the duplicate work of adding to the cache and to ES if another message handler raced us.

as for:

> You already add the metricDef here.... so the  Isnt needed.

you're right, adding to defcache twice is redundant. but i would rather then remove the adding to defcache from the addToEs function, so that we at least always have the metricdef in the defcache, even when addToEs fails. your commit will not add the mdef to defcache if queue-to-ES returned an error. why is this? it seems very useful to me always try to have the metricdef in defcache at least.

**Comment by woodsaj** [comment]
>your commit will not add the mdef to defcache if queue-to-ES returned an error. why is this?

From my comment above

>If we cant write to the bulkIndexer then we would need to retry the next time we see the metric. If we added the metricDef to the cache and metricdef.IndexMetric(mdef) failed then we would not retry to index it for many hours.

**Comment by Dieterbe** [comment]
ah ok missed that, that makes sense :+1: 

what do you think of the first part of my previous comment?

**Comment by woodsaj** [comment]
I think the performance gain from not having the additional lock for every metric is far greater the any gain from not sending duplicate metricDefs to ES on the rare occasion two handlers process the same metric at the same time.  After all, the metricDef.IndexMetric function really only just adds the metricDef to the bulkIndexer buffer.

**Comment by Dieterbe** [comment]
fair enough.
