### ISSUE TITLE
make sure blocking profiling works

### ISSUE THREAD

**Issue by Dieterbe** [raintank/raintank-metric#149]
it may hold the key to while ingest jammed when cassandra was slow for gets.
i got some profiles during the outage but they just contain
```
--- contention:
cycles/second=2300001382
```
maybe we need to upgrade our go version.

**Comment by woodsaj** [comment]
Everything running in our stack is built in Circleci jobs. Circleci uses GO 1.5.1

**Comment by Dieterbe** [comment]
the missing piece was 89d8db8959cb630616c72946d354452d7e2629a2
