### ISSUE TITLE
Requests that cant be served from memory shouldn't be sent to Cassandra

### ISSUE THREAD

**Issue by woodsaj** [raintank/raintank-metric#152]
Outages over the last couple of days have shown that when there is a delay consuming metrics from NSQ, requests generated by the grafanaAlerting are being sent to cassandra.  Cassandra is unable to handle this rate of requests.

The issue occurs when the "from" time of the requested range is greater then any timestamp that would be stored in the current chunk.  Ie if the chunks are storing 10minutes of data and the current chunk started at 00:10, then requests for points "from" 00:20 or later can not be met.
https://github.com/raintank/raintank-metric/blob/master/metric_tank/aggmetric.go#L231-L235

When this happens we should not be trying to request the data from Cassandra.  We should instead just return nulls, as there is no data.

**Comment by Dieterbe** [comment]
i think 014e9e5a8e273aab269beb3244ecf670e1e81c96 covers it.
