### ISSUE TITLE
MT: secure graphite endpoint

### ISSUE THREAD

**Issue by Dieterbe** [raintank/raintank-metric#177]
as of #176 we have a very basic graphite endpoint, without search/autocomplete, wildcards, functions.
goals are 1) support direct testing of a specific instance 2) move over alerting queries cause they don't  use fancy graphite logic and 3) long term use it directly as a graphite replacement.

we should make sure tenants are only capable of seeing the data they have access to. we could do a simple org-id check like graphite-raintank does. it's just that it's clunky to use since our grafana fork (and the litmus app presumably) just has 1 hardcoded raintank datasource, and when you add the new datasource as a graphite datasource it won't set the right header..or maybe we can add it as a built-in datasource as well ("raintank-beta") or something, that way we can make sure it sets the header

@woodsaj am i thinking along the right lines or am i way off?

**Comment by woodsaj** [comment]
users should not ever be hitting metric-tank directly.  They need to go via a proxy which can handle the authentication and routing to one of many metric-tank instances.  As we move to grafana.net this will look something like
https://github.com/raintank/raintank-apps/tree/master/tsdb

as for the new graphite endpoint add in https://github.com/raintank/raintank-metric/pull/176, it will not work as it is not multi-tenant.  You are indexing the metricDefs by the Name field, but this name field is only unique to 1 user.

**Comment by Dieterbe** [comment]
closing this ticket since the question was answered and there's tickets for everything else
