### ISSUE TITLE
just use the grafana models?

### ISSUE THREAD

**Issue by Dieterbe** [raintank/raintank-metric#19]
instead of our own models, can we just use what's in github.com/grafana/grafana/pkg/models ?
seems like the only difference is the Id field used for ES indexing.

**Comment by woodsaj** [comment]
There are two models needed.  1 for metric instance with timestamp and value, and 1 used for indexing in elasticsearch.    The difference between the metric_with_value and metric_index are currently minor, but this is likely to change over time.

metric_with_value is the model that is shared between grafana and raintank-metric (and raintank-probe/collector) and so should be stored in just one place.  We should also provide the helper methods for encoding/decoding into different versions (json, msgpack, protobuf etc...)

the metric_index model is only needed by raintank-metric and will always be marshalled to JSON as that is the format used to send the index to elasticsearch.

**Comment by woodsaj** [comment]
i think that we should define the model outside of grafana and inside raintank-metric.  The main reason being that we are using a fork of grafana, so the imports will reference github.com/grafana/grafana though we really want github.com/raintank/grafana

**Comment by Dieterbe** [comment]
yeah so i meant `metric_with_value`. it'd be nice to only have it defined in 1 place.
in here and out of grafana sounds fine with me.
if we want to add extra fields such as id, we could just define a struct that anonymously embeds the "base" struct and we could probably just decode into the new one, leaving the extra fields at their default values. (it would be annoying have to copy data from one struct type to another)

re elasticsearch, looks like over time we can pick something better than json too, see
https://www.elastic.co/guide/en/logstash/current/codec-plugins.html
in particular:
https://www.elastic.co/guide/en/logstash/current/plugins-codecs-msgpack.html

**Comment by woodsaj** [comment]
elasticsearch is a document database.  The documents must be in json as that is the only format supported by the API

**Comment by Dieterbe** [comment]
fixed in nsq branch of raintank-metric and grafana.
both metrics and events now use a shared schema, defined in the raintank-metric repo.
