### ISSUE TITLE
rollups should align to minute boundary

### ISSUE THREAD

**Issue by woodsaj** [raintank/raintank-metric#2]
Currently when the metric consumer starts the rollup period is based on the time the first metric is received.  If the consumer restarts, then a new rollup period will be used.

Aligning the rollup period to consistent boundaries should fix this and provide more consistent results.

**Comment by ctdk** [comment]
This is also now in place in master. The rollup data is stored in redis for consistency and to keep it intact across restarts. There's also some relatively simple locking in place to keep data from being overwritten by different goroutines or processes.
