### ISSUE TITLE
invalid memory address or nil pointer dereference @ metric_tank/mdata/aggmetric.go:309

### ISSUE THREAD

**Issue by Dieterbe** [raintank/raintank-metric#210]
see https://github.com/raintank/ops/issues/286

**Comment by Dieterbe** [comment]
> a.getChunk() can return nil, but this is not inspected before trying to use it.

@woodsaj I believe inspecting for nil and ignoring nil chunks in that case would be masking the problem instead of solving it.
getChunks should only return nil if the requested index was < 0 or > len(a.Chunks) which should not happen. if this happens it's a code bug, not a runtime error to be handled. looking at the Get() code, it's clear we will never request such a faulty index except in one case:
https://github.com/raintank/raintank-metric/blob/master/metric_tank/mdata/aggmetric.go#L311 here we chunk for NumChunks instead of len(a.Chunks)

**Comment by Dieterbe** [comment]
as per the above, i think this is the right fix https://github.com/raintank/raintank-metric/pull/211

**Comment by Dieterbe** [comment]
i was partially wrong: in a few places we were calling `a.getChunk(0)` and relying on the behavior to get nil back as a means to tell we don't have any chunks yet.

this is:
* needlessly complicated, can simply check `len(a.Chunks) == 0` instead
* means that calls where the pos gets badly calculated to 0 become handled at runtime instead of making it clear to the programmer there's a bug.
* bugs where the pos gets badly calculated to >= len(a.Chunks) get masked as simply "we don't have data" whereas it's clearly a bug to be fixed.

**Comment by Dieterbe** [comment]
and btw, closing argument: we currently have 30 hardcoded panic() calls throughout the MT codebase, yet i don't recall any of them causing prod disruption. Why? because they force us to solve the problems so the panics don't actually end up triggering. If they ever do, we know it'll be fixed soon. That's much more than what can be said of logging errors.

**Comment by Dieterbe** [comment]
tested a bit in raintank-docker, patch seems to work fine. (not extensively tested)

**Comment by woodsaj** [comment]
I just comitted a small change to fix the actual problem so we can deploy the changes to production and stop the outages, as that is the primary concern.  PR #211 is nice, but we cant wait for discussions on how to handle panics to be had before restoring our production environment.
