### ISSUE TITLE
nsqd_metrics_to_elasticsearch needs flag to point to ES

### ISSUE THREAD

**Issue by Dieterbe** [raintank/raintank-metric#22]
right now it seems to default to `elasticsearch`.
once fixed, should also remove the `/etc/hosts` entry.

**Comment by Dieterbe** [comment]
same for probe_events

**Comment by Dieterbe** [comment]
also "redis"

**Comment by Dieterbe** [comment]
also "kairosdb"

**Comment by Dieterbe** [comment]
fixed in https://github.com/raintank/raintank-metric/commit/9c49c9540b8923a280147f12ef210fa9c0d640ef

as for how to use, see https://github.com/raintank/raintank-docker/commit/662962049a580c7a987f12cbc2f7a71c53376bbe

@ctdk can you take it from here?

**Comment by Dieterbe** [comment]
oh also the `-n` option is now gone. so the `-n 0` should be removed.

**Comment by ctdk** [comment]
Right-o.

**Comment by ctdk** [comment]
The new nsq_* packages with this are build properly (the out of date binaries are fixed) and up on the kairos and elasticsearch boxes we're currently running those on, and everything's running as smoothly as can be expected. I'll address that in a different ticket.

**Comment by Dieterbe** [comment]
> I'll address that in a different ticket.
address what? you just said everything went great?

**Comment by ctdk** [comment]
The "smoothly as expected" part I addressed in the provisioning collector controllers ticket. ckg-ssd-1 was groaning a bit for a while, but not breaking, so I wanted to float installing the nsq_* tools elsewhere, but it didn't seem appropriate in here.
