### ISSUE TITLE
support configuration file for services

### ISSUE THREAD

**Issue by woodsaj** [raintank/raintank-metric#27]
Either the apps themselves need to support a configuration file for loading settings, or the init script needs to support using an external file (/etc/default/<serviceName>) for defining the options passed on the command line.

It is not practical to have deb/rpm packages that require users to modify the init scripts in order for the  server to work correctly in their environment.

see: https://github.com/raintank/ops/issues/133

**Comment by ctdk** [comment]
PR for this: https://github.com/raintank/raintank-metric/pull/45

**Comment by ctdk** [comment]
This has been merged.
