### ISSUE TITLE
move tag sorting / id generation to MetricData creation

### ISSUE THREAD

**Issue by Dieterbe** [raintank/raintank-metric#29]
(i'm using the shorthands here, see https://github.com/raintank/raintank-metric/blob/master/README.md)
currently, `*schema.MetricData.Id()` is called:
* in nme at every datapoint for each series, to look up and save metric definition
* in nmt at every datapoint for each series, needs to lookup the AggMetric structure  (not yet, but should)
* not in nmk , doesn't seem to call `Id()` but this service will most likely be deprecated

this operation, especially when called so often, is expensive: it has to sort the tag strings, allocates a buffer and a few temporary strings and calls Printf a bunch of times.
while these services are always in flux, it's clear that this will operation will happen more frequently in the consumers than in the producers.

solutions:
A) sort the tags when we create the MetricData instance, so that `Id()` can skip that step (but still repeatedly does the other work)
B) pre-generate the Id field at MetricData creation time, and store it as a member of the struct

I think we should do A+B, but i also think this is low priority. we can address it when it becomes more of a real problem.
 what do you think @woodsaj ?

**Comment by woodsaj** [comment]
"id" should be a property of the metric and not a method.  We should set it at the ingestion point (collector-controller) and pass it through to all consumers.

**Comment by Dieterbe** [comment]
AJ committed the fix on jan31: https://github.com/raintank/grafana/commit/326a98aa064d248105fc18004852d8307e7ee450

i can confirm all incoming metrics into MT have the id field set.
see also #137
