### ISSUE TITLE
graphite-watcher metrics seem broken

### ISSUE THREAD

**Issue by woodsaj** [raintank/raintank-metric#39]
![image](https://cloud.githubusercontent.com/assets/8415072/10764463/51b7def0-7d09-11e5-9b94-6449e2560dc3.png)

The lag values just grow linearly, even when there is no load on the stack.  What are these values supposed to be showing?

**Comment by Dieterbe** [comment]
time difference between now and the oldest null of a given metric.
i.e. the gap between the last valid datapoint and now.
this shows how recent the data is in graphite.

if it's constantly raising, i think there's metrics being returned by ES that are not receiving any new data.

the lag is constantly checked on a random metric from what's currently in ES, at 10 per second.

**Comment by Dieterbe** [comment]
FWIW on my stack it stays around mean 0, max 6s
and when the #37 bug manifests, the metrics also keep raising up but you're still at 1.2k so that doesn't apply here.

**Comment by woodsaj** [comment]
> time difference between now and the oldest null of a given metric.
> i.e. the gap between the last valid datapoint and now.

These 2 statements are not the same thing.  The oldest null == the first null, and will never change.
 "the gap between the last valid datapoint and now." would be the time between now and the "last non  null" value

**Comment by Dieterbe** [comment]
right. it's not the oldest null in an absolute sense, it has to be a point within the range that we expect to have data (i.e. after we see the metric in ES).
and i skimped over an implementation detail, if there's no nulls, we take last-non-null-value+step to mean "oldest null". so it's never from a "non null value", always the null value after that (if exists), or just "last non null value" + step to be the "implied" null value (this scenario is pretty good and results in a lag of around 0 i think)

**Comment by Dieterbe** [comment]
for more details, the source code should be fairly straightforward.

**Comment by woodsaj** [comment]
so i have read the code. The code is definitely assigning lag as "time difference between now and the oldest null of a given metric."  it is not setting lag to "the gap between the last valid datapoint and now" which from your description it should be.

graphite-watcher is querying the last 24hours of data.  Lag is being calculated as the time since the "first" null value in that set. So if the collector is restarted resulting in no data being sent for a short period, then the lag will steadily grow to 24hours.

**Comment by Dieterbe** [comment]
hmm right. i've been going under the assumption that for these benchmark runs, we wouldn't restart collectors, and any drop of data justifies invalidating the benchmark results.
we need to have a steady stream of uninterrupted data to make fair comparisons between stacks.

**Comment by woodsaj** [comment]
https://github.com/raintank/raintank-metric/blob/tank/graphite-watcher/main.go#L143-L146

assume the following data.
#[value, ts]
```
[null, 1446002246]
[0, 1446002247]
[0, 1446002248]
[null, 1446002249]
```

With the current code oldestNull is set to 1446002246 , so the lag is determined to be 4seconds, instead of the expected 1 second.

This seems trivial to fix, if 
```
_, err = p[0].Float64()
if err == nil {
  oldestNull := int64(math.MaxInt64)
}
```

**Comment by woodsaj** [comment]
>we need to have a steady stream of uninterrupted data to make fair comparisons between stacks. 

agreed, but that is a completely different problem to measuring the delay between metrics being created and being available for querying by graphite.

**Comment by Dieterbe** [comment]
i see your point. right now we do get both the "true delay" measurement and dataloss measurement at once, though the latter is very crude (lag going up at same rate as time moves on means there was a drop in data).  for these benchmarks i don't think we necessarily need to be more fancy than this.  (since any high lag or metric data drops warrants invalidating the run and both are covered)

i'm open to separating them out though, so we can handle and visualize them each more properly.
it'll be less confusing about what's going on and also let's us use graphite-watcher in our actual stacks instead of articifial benchmark environments.

want to give this a shot? :)
