### ISSUE TITLE
when rolling up data compute median as well as average(mean)

### ISSUE THREAD

**Issue by woodsaj** [raintank/raintank-metric#4]
Currently when showing aggregated data, we are seeing numerous large spikes in the graphs. This typically happens when for example, a HTTP connect spikes from 30ms to 2000ms likely due to a lost syn packet.  Though this is valid data, these individual points significantly affect the averages being computed when rolling up.  

By storing the median value, we will help to improve the user experience and show smoother graphs, which are a better representation of the performance of an endpoint.

**Comment by ctdk** [comment]
Put something in for this in the "median" branch until I get my docker woes ironed out and can actually test it.

**Comment by ctdk** [comment]
This has been merged into master.
