### ISSUE TITLE
support clean restarts of NMT

### ISSUE THREAD

**Issue by woodsaj** [raintank/raintank-metric#40]
When a shutdown is initiated, NMT needs to stop:

* stop consuming from NSQ
* flush all aggemetrics to disk
* exit

when starting up we need to:

* load all aggemetrics from disk
* start consuming from NSQ

This allows us to restart NMT without experiencing data loss. This is necessary as we plan to deploy an  early version and frequently iterate on it.

**Comment by woodsaj** [comment]
Made good progress on this today. Still a few things to clean up, like being able to set the path/filename of where the data is written to.

@Dieterbe This change also required me committing changes to go-tsz.  I committed the changes to https://github.com/raintank/go-tsz/tree/raintank-dev as that appeared to be the most recently updated branch.

What is needed to get our changes merged into master of go-tsz?

**Comment by Dieterbe** [comment]
> What is needed to get our changes merged into master of go-tsz?

create topic branches that just contain the relevant commits (you can use git cherry-pick) and file PR's against them.

some commits probably shouldn't be contributed upstream (like https://github.com/raintank/go-tsz/commit/66e06c3c5c1c8e7dc25303272d36684af4464ef5)

i already have a PR of mine merged in it, i'll check the other commits of mine in our fork and PR them if it makes sense

**Comment by woodsaj** [comment]
This has been completed.  We are just using github.com/raintank/go-tsz until our PRs are merged upstream

**Comment by Dieterbe** [comment]
:+1:
