### ISSUE TITLE
update build scripts to build raintank-tank package

### ISSUE THREAD

**Issue by woodsaj** [raintank/raintank-metric#44]
need to update pkg/* to build nsq_metrics_tank (we should name the package as raintank-tank if possible.

**Comment by ctdk** [comment]
@woodsaj Re: renaming, do you mean rename raintank-metric raintank-tank, or just renaming nsq_metrics_tank to raintank-tank?

**Comment by ctdk** [comment]
Packages build and are installable. Not closing until the renaming bit is clarified.

**Comment by woodsaj** [comment]
@ctdk just the nsq_metrics_tank package should be named raintank-tank

**Comment by ctdk** [comment]
Tying into https://github.com/raintank/raintank-metric/issues/27 and https://github.com/raintank/raintank-metric/pull/45, the packaging now includes config files for the packages with reasonable defaults (although not correct for us - chef will handle that), and the upstart configs now use the `-config` flag. This will cause apt-get to blow up when chef tries to deploy them, but it's fixable (just a bit annoying).

**Comment by ctdk** [comment]
I think this is done now, seeing as it's on dev-portal and all.
