### ISSUE TITLE
use grafana log library for logging in all tools

### ISSUE THREAD

**Issue by woodsaj** [raintank/raintank-metric#51]
metric-tank has already been updated to use github.com/grafana/grafana/pkg/log, the other nsq_* tools also need to be updated.

This will allow us to turn down the log volume.

**Comment by woodsaj** [comment]
nsq_metrics_to_elasticsearch has been updated.  in https://github.com/raintank/raintank-metric/pull/52

**Comment by Dieterbe** [comment]
@ctdk you were working on this right, what's the status of this? can this be closed

**Comment by ctdk** [comment]
It got merged, so yes.
