### ISSUE TITLE
bug: state reloading indistinguishable from black magic

### ISSUE THREAD

**Issue by Dieterbe** [raintank/raintank-metric#55]
in devstack:
1) i add 1 endpoint at 9:50, so it starts accumulating data, graphs start getting data.
2) at 10:00 i check in nsqadmin that there's 0 backlog, NMT is 100% up to date. all graphs have data from 9:50 until 10:00
3) i kill metric_tank, `rm /tmp/nmt.gob` and restart it. it says `starting with fresh aggmetrics`
4) i reload the graphs in grafan. *all the data since 9:50 is still there!* i thought maybe it's caching but:
```
root@graphite:/# grep -i cache /var/log/raintank/graphite-*
/var/log/raintank/graphite-api.log:/usr/local/lib/python2.7/dist-packages/flask_cache/__init__.py:152: UserWarning: Flask-Cache: CACHE_TYPE is set to null, caching is effectively disabled.
/var/log/raintank/graphite-api.log:  warnings.warn("Flask-Cache: CACHE_TYPE is set to null, "
```
also, zooming in grafana still shows the data (so it's not caching by to/from)

where is the data coming from? in network tab, i see requests being made to `http://localhost/api/graphite/render` and responding properly

**Comment by woodsaj** [comment]
The data will be coming from cassandra.

If you want to test easily, increase the chunkspan setting to 30minutes.  Then after 15minutes kill metric_tank and delete /tmp/nmt.gob.  WIll 15minutes of data will then be lost.  Also make sure you dont kill just after the chunkspan boundary.  i.e, if the chunkspan is 10mins and you kill the app just after 10,20,30,40 or 50 minutes passed the hour, the data will already have been written to C*

**Comment by Dieterbe** [comment]
ah of course... played with a bit more now. how could i miss this :)
