### ISSUE TITLE
let's switch tank back to go-metrics instead of statsd

### ISSUE THREAD

**Issue by Dieterbe** [raintank/raintank-metric#62]
* i'm not a fan of https://github.com/raintank/raintank-metric/commit/56d3a076add9fc410a7caf64a7b54f588bfb8963, the pointsPerMetric stat is quite valuable, especially in prod. i tried out a change where we just collect this metric without all the additional goroutines and without having to lock the `AggMetrics` for each metric (https://github.com/raintank/raintank-metric/commit/262ad852364a4ddf2ed793a31206fe302b03eb5d), but the profile still reveals that we spend almost all of our time in statsd udp writes

```
(pprof) top30 -cum
4.95s of 12.66s total (39.10%)
Dropped 319 nodes (cum <= 0.06s)
Showing top 30 nodes out of 199 (cum >= 0.90s)
      flat  flat%   sum%        cum   cum%
     0.01s 0.079% 0.079%      9.78s 77.25%  runtime.goexit
     0.03s  0.24%  0.32%      4.56s 36.02%  github.com/Dieterbe/statsd-go.(*Client).Send
     0.03s  0.24%  0.55%      4.32s 34.12%  net.(*conn).Write
     0.04s  0.32%  0.87%      4.29s 33.89%  net.(*netFD).Write
     4.02s 31.75% 32.62%      4.20s 33.18%  syscall.Syscall
     0.01s 0.079% 32.70%      3.98s 31.44%  syscall.Write
     0.01s 0.079% 32.78%      3.97s 31.36%  syscall.write
     0.03s  0.24% 33.02%      3.93s 31.04%  fmt.Fprintf
     0.02s  0.16% 33.18%      3.14s 24.80%  github.com/grafana/grafana/pkg/metric/statsd.(*Meter).Value
     0.02s  0.16% 33.33%      3.12s 24.64%  github.com/grafana/grafana/pkg/metric/statsd.Meter.Value
     0.03s  0.24% 33.57%      3.10s 24.49%  github.com/Dieterbe/statsd-go.(*Client).Timing
```

getting the graph with the web command confirms that all the conn writing is caused by the statsd client
![statsd-overhead](https://cloud.githubusercontent.com/assets/20774/11412619/f040d0d0-9443-11e5-9c9c-876cb028fe07.png)
as i've mentioned before, there are some things we could do (sampling, pre-computing, buffering udp writes) but ultimately all those are still workarounds for the fact that udp writes come with an overhead, and frankly i don't think any of us have time right now to work on optimizing that. there are some other golang statsd clients that may be more advanced but it takes time to evaluate them cause in my experience there's always a lot of subtle differences between different clients.

go-metrics is based on a much nicer model IMHO. it can just compute the metrics in-process and stream them straight to graphite, or to $whatever, and also expose them via expvar (json over http)
in my experience it works quite well.

**Comment by Dieterbe** [comment]
@woodsaj can i get an okay on this. i really want pointsPerMetric back.

**Comment by woodsaj** [comment]
No.  But maybe later.

I dont want to be running two metrics libraries, and we are not in a position to be able to refactor all of our other projects to use go-metrics right now.

For "pointsPerMetric" specifically, what additional insight does it provide that "chunk_size.at_save" doesnt?

pointsPerMetric may be valuable to you, but there is no way its value out ways the cost of the huge performance penalty of scanning the entire in-memory DB of metrics periodically (unless it is scanning frequency is once per hour or less)

**Comment by Dieterbe** [comment]
PointsPerMetric is number of points, chunk_size is in bytes. basically PointsPerMetric is what you need to make sense out of the memory usage and of the chunk sizes. without knowing how many points there are, we can't really make judgements on chunk sizes and RAM usage in terms of normal vs more optimizations needed vs something's wrong. and it's really valuable for this to be a distribution.

**Comment by woodsaj** [comment]
@Dieterbe can we then just collect this metric when we persist the chunk?

**Comment by Dieterbe** [comment]
that's not gonna solve the problem, the high overhead of the statsd client. also this would skew the stats a lot, we need realtime usage.
I think we should just report it via go-metrics, i see your point about not wanting multiple metrics libraries but it's only a small annoyance for a big gain.

**Comment by woodsaj** [comment]
the overhead of the statsd client is only a small part of the problem.  The bigger problem is scanning the entire dataset every second, even though the data set is 99.99% the same between scans.

**Comment by Dieterbe** [comment]
look at the profile in OP.

**Comment by woodsaj** [comment]
if you perform 300k/second writes to a socket, then obviously the write path is going to account for the majority of the process workload.  

If you instead only perform 500/second writes to the socket the problem goes away.

**Comment by Dieterbe** [comment]
yes i know.. who has spare time to spend optimizing the stastsd client or evaluating other clients and porting to them. seems like a lot more work to me. i'm just repeating myself at this point.

**Comment by woodsaj** [comment]
i think you are missing the point.

you cant do this:

https://github.com/raintank/raintank-metric/blob/master/metric_tank/aggmetric.go#L86-L101

it doesnt matter what stats library you use, you can't call it many hundreds of thousands of times per second.  Having all of the goroutines contending for CPU time and scanning the entire data set every second is the thing that is wrong with that code.

**Comment by Dieterbe** [comment]
FTR:
i profiled the variant i mentioned in OP, without all the goroutines (https://github.com/raintank/raintank-metric/commit/262ad852364a4ddf2ed793a31206fe302b03eb5d) but with statsd disabled and cpu profiling showed that 2.13% of time was spent in `main.(*AggMetric).stats` and everything called by that. this was under a 2k/s ingest load and no http requests load. However hooking in go-metrics raised this to 15%
Currently `MetricDef.Id()` is the biggest cpu user, once we optimize that, the rest (including stats) would be a higher as a %.  While adding a http requests load to the mix would bring the % down, you did convince me this level of stats accuracy is not worth it and should only be done to in specific debug / reproduction cases. 

So I'll see about adding a more lightweight form of this metric back in, something light on cpu (incl statsd). maybe a gauge of total points in the process or something.

**Comment by Dieterbe** [comment]
see #73
