### ISSUE TITLE
too high cpu usage

### ISSUE THREAD

**Issue by Dieterbe** [raintank/raintank-metric#8]
my laptop has 8 `Intel(R) Core(TM) i7-4810MQ CPU @ 2.80GHz` cores. 
i'm running the devstack, with just 1 endpoint configured with 3 checks every 10seconds.
in top, raintank-metric is running with 80 to 180% cpu. this seems like way too much.

i suggest importing `_ "net/http/pprof"` and creating a http listener, so that when cpu % is high, we can get performance profiles at `<tcp_addr>/debug/pprof/` (probably should expose the http port through docker as well)

this is the first time i see this though, btw. maybe it only happens in certain conditions. but i'll keep an eye on it and would love to give you a profile next time.

**Comment by woodsaj** [comment]
The cpu usage should not be that high.  my dev box in digitalOcean is running the full stack and it only has 2GB Ram 2x2.4GHZ.  I have 2 endpoints configured and 2 collectors running and CPU usage of raintank-metric is less then 1%.
