### ISSUE TITLE
aggSettings need to include a field for TTL when writing data to cassandra.

### ISSUE THREAD

**Issue by woodsaj** [raintank/raintank-metric#82]
There is  "TTL" config option that is used when writting raw data and aggregated data to cassandra.
However, the various aggSettings should have their own TTL values as we will be storing the different resolution data for different time periods.  eg. raw for 1month, 1h rollups for 6months and 6h rollups for 2years

**Comment by woodsaj** [comment]
Looks like this can be done by adding a ttl field to the AggMetric Struct and extending the aggSettings schema.

**Comment by Dieterbe** [comment]
sounds good.
