### ISSUE TITLE
deadlock when trying to push many chunks into the writeQueue

### ISSUE THREAD

**Issue by woodsaj** [raintank/raintank-metric#84]
if the number of old chunks that need to be written to the writeQueue is greater then the length of the writeQueue, we can encounter a deadlock situation.

This is because the goroutine draining the writeQueue will try and get a Lock on the aggMetric when the queue is empty.  But there could be a goroutine that already has the lock that is about to write many chunks to the writeQueue.  The goroutine draining the queue will be blocked and no items will be getting drained, and the goroutine writing to the queue will block once it has written MaxUnwrittenChunks.

**Comment by Dieterbe** [comment]
@woodsaj question about this: since pending is in reverse chronological order, wouldn't this cause persisting the newer chunks and bypassing persisting the oldest chunks? and wouldn't that cause those chunks to be never considered again?

**Comment by Dieterbe** [comment]
oh my mistake, you are getting the last part of pending, i didn't look carefully.
