### ISSUE TITLE
production graphs showing metrics with values in the trillions. which is not possible

### ISSUE THREAD

**Issue by woodsaj** [raintank/raintank-metric#87]
![trillionvaluepoint](https://cloud.githubusercontent.com/assets/8415072/11960226/952c4bd8-a90c-11e5-83b1-e9dba8d33c9d.png)

From a quick look at the data in cassandra, looks like some leading 0's are being missed.
First select is valid data, second select is the chunk where the first value is 9.22 trillion

```
cqlsh:raintank> SELECT ts, data FROM metric WHERE key='1.9ba599efc9c4747d9e9729416de0b5e0_599' AND ts >= 1450253400 limit 2;
 ts         | data
------------+--------------------------------------------------
 1450800600 | 0x00567975d80014ffc00000000000026e0000fffffffff0
 1450800000 | 0x00567973800014ffc00000000000026e0000fffffffff0
(2 rows)
cqlsh:raintank> SELECT ts, data FROM metric WHERE key='1.9ba599efc9c4747d9e9729416de0b5e0_599' AND ts = 1450253400 limit 1;
 ts         | data
------------+------------------------------------------------
 1450253400 | 0x56711c580014ffc00000000000026e0000fffffffff0
(1 rows)
```

**Comment by Dieterbe** [comment]
the 0x00 prefix of the first 2 chunks is probably the version byte. the older data may have been created with older code that didn't have the version header yet? @woodsaj did tihs problem happen after your "support missing version byte" commit?

**Comment by woodsaj** [comment]
yes, this problem is from after this commit was deployed to prod. https://github.com/raintank/raintank-metric/commit/cb9b2980cf07d286f27d335a4c7fb10bf6d2b5a0

**Comment by Dieterbe** [comment]
and we're sure it was compiled with the latest https://github.com/raintank/go-tsz right?  so https://github.com/raintank/go-tsz/commit/2d496e2f4e151a0f31ef9679d26bf07cd30508eb should be in there.
before we start debugging the chunk byte by byte, can we get the values in kairosdb for 1450253400 and the next few points?

**Comment by woodsaj** [comment]
Ok. confirmed that this is not an issue with metric-tank, as the same 9.2Trillion value is also in Kairosdb.

will open an issue in raintank-probe.

![trillionvaluepointkairosdb](https://cloud.githubusercontent.com/assets/8415072/11972772/ddd4c192-a98b-11e5-8a57-88e0d40900bc.png)

**Comment by Dieterbe** [comment]
yeay :)
