### ISSUE TITLE
"multiple series with same key" handled incorrectly

### ISSUE THREAD

**Issue by Dieterbe** [raintank/raintank-metric#92]
old logic in case of 2 metrics with different id but same key (e.g. in litmus, when deleting and endpoint and then re-adding it): collect non-null data of both, which are guaranteed to cover different timespans, merge them, and add nulls where appropriate.

as I brought up in https://github.com/raintank/graphite-raintank/pull/14#issuecomment-165349496 , the various changes introduced by that PR also have a side effect: MT will add nulls to both series independently  first and then return em like that and we'll have a hard time merging them back together. IIRC since my PR they don't even get merged together at all anymore.

**Comment by woodsaj** [comment]
I think the simplest way to solve this is to have graphite-raintank merge the series.

**Comment by Dieterbe** [comment]
Or maybe MT can do the merging?

**Comment by woodsaj** [comment]
certainly possible, but it would still be simpler to do it in graphite-raintank.

**Comment by woodsaj** [comment]
closing this out.  Nothing more to be done here.  We can revisit this when we work on graphite-ng

**Comment by Dieterbe** [comment]
for the record, this was fixed through https://github.com/raintank/graphite-raintank/pull/18
